stages:
  - build
  - report
image: aventusrob/aventus-dotnet-azcli:1.0

before_script:
    - cd $CI_PROJECT_DIR;ls

build:
  stage: build
  script:
    - mkdir TestResults
    - ResultsDir=$(realpath  TestResults/)
    - mkdir $ResultsDir/css
    - cd $CI_PROJECT_DIR;dotnet run
    - cp $CI_PROJECT_DIR/Reports/index.html $ResultsDir/index.html
    - cp $CI_PROJECT_DIR/Reports/platform.html $ResultsDir/platform.html
    - cp $CI_PROJECT_DIR/Reports/style.css $ResultsDir/style.css
    - cp $CI_PROJECT_DIR/Reports/normalize.css $ResultsDir/normalize.css
  artifacts:
    when: always
    paths:
      - TestResults/*.html
      - TestResults/*.css
      
pages:
  stage: report
  script:
    - cp -r TestResults/ ./public
    - cd public;ls
  dependencies: 
    - build    
  artifacts:
    paths:
     - public
    
