using System;
using System.Collections.Generic;
using System.Reflection.Metadata;
using System.Text;

namespace test_reports.APITestCoverageReport
{
    public class EndpointsMap
    {
        public Dictionary<string, Tuple<string, string>> OpusEndpointsMap()
        {
            var dictionary = new Dictionary<string, Tuple<string, string>>
            {
                {"Run a command",  new Tuple<string,string>( "POST /v1/command","Command") },
                {"Describe a command", new Tuple<string,string>("GET /v1/command/describe/{command}", "Command") },
                {"Get organisation settings",  new Tuple<string,string>( "GET /v1/config/organisation","Config") },
                {"Send policy documents to a provided email address", new Tuple<string,string>("POST /v1/document/email/policy", "Document") },
                {"Send quote documents to a provided email address", new Tuple<string,string>("POST /v1/document/email/quote", "Document") },
                {"Add a note to a quote document", new Tuple<string,string>("POST /v1/notes/quote/{quoteID}", "Notes") },
                {"Get notes for a quote", new Tuple<string,string>("GET /v1/notes/quote/{quoteID}", "Notes") },
                {"AddOrgClaim", new Tuple<string,string>("POST /v1/opusorgs/claims/add", "Opus Organization Management") },
                {"GetAllOrgClaims",new Tuple<string,string>("GET /v1/opusorgs/claims/list", "Opus Organization Management") },
                {"RemoveOrgClaim", new Tuple<string,string>("POST /v1/opusorgs/claims/remove", "Opus Organization Management") },
                {"Add Group", new Tuple<string,string>("POST /v1/opusorgs/groups/add", "Opus Organization Management") },
                {"List Groups", new Tuple<string,string>("POST /v1/opusorgs/groups/list", "Opus Organization Management") },
                {"GetUser", new Tuple<string,string>("GET /v1/opususers/{userID}", "Opus User Management") },
                {"Update User", new Tuple<string,string>("PUT /v1/opususers/{userID}", "Opus User Management") },
                {"Remove User", new Tuple<string,string>("DELETE /v1/opususers/{userID}", "Opus User Management") },
                {"AddUser Claim", new Tuple<string,string>("POST /v1/opususers/{userID}/claims/add", "Opus User Management") },
                {"Remove User Claim", new Tuple<string,string>("POST /v1/opususers/{userID}/claims/remove", "Opus User Management") },
                {"Disable User", new Tuple<string,string>("POST /v1/opususers/{userID}/claims/disable", "Opus User Management") },
                {"Add User Group", new Tuple<string,string>("POST /v1/opususers/{userID}/groups/add", "Opus User Management") },
                {"Remove User Group", new Tuple<string,string>("POST /v1/opususers/{userID}/groups/remove", "Opus User Management") },
                {"Add User", new Tuple<string,string>("POST /v1/opususers/add", "Opus User Management") },
                {"Get All Users", new Tuple<string,string>("GET /v1/opususers/list", "Opus User Management") },
                {"Get All Users With Claims", new Tuple<string,string>("POST /v1/opususers/list/claims", "Opus User Management") },
                {"Get Payment", new Tuple<string,string>("GET /v1/payments/{paymentId}", "Payment") },
                {"Get Policy For Payment", new Tuple<string,string>("GET /v1/payments/{paymentId}/policy", "Payment") },
                {"Create Finance Agreement", new Tuple<string,string>("POST /v1/payments/finance", "Payment") },
                {"Update Finance Agreement for mid term adjustment", new Tuple<string,string>("POST /v1/payments/finance/mta", "Payment") },
                {"Initialise Payment", new Tuple<string,string>("POST /v1/payments/initialise", "Payment") },
                {"Refund for a mid term adjustment", new Tuple<string,string>("POST /v1/payments/mtarefund", "Payment") },
                {"One step payment", new Tuple<string,string>("POST /v1/payments/onestep", "Payment") },
                {"Apply Voucher", new Tuple<string,string>("POST /v1/payments/voucher", "Payment") },
                {"Gets Policy By Id", new Tuple<string,string>("GET /v1/policies/{policyId}", "Policy") },
                {"Get Policy Bundle", new Tuple<string,string>("GET /v1/policies/{policyId}/bundle", "Policy") },
                {"Get Policy Credit Agreement", new Tuple<string,string>("GET /v1/policies/{policyId}/creditagreement", "Policy") },
                {"Get Policy Document Content",new Tuple<string,string>("GET /v1/policies/{policyID}/debugpolicydocumentdata", "Policy") },
                {"Get Policy Discount details", new Tuple<string,string>("GET /v1/policies/{policyId}/discountinfo", "Policy") },
                {"Get Policy Risk", new Tuple<string,string>("GET /v1/policies/{policyId}/risk", "Policy") },
                {"Cancel Policy", new Tuple<string,string>("POST /v1/policies/cancel", "Policy") },
                {"Get Policy Cancellation Information", new Tuple<string,string>("GET /v1/policies/cancel/{policyId}/info", "Policy") },
                {"Gets Policies by user Id", new Tuple<string,string>("GET /v1/policies/list", "Policy") },
                {"Gets Policy by reference", new Tuple<string,string>("GET /v1/policies/reference/{policyReference}", "Policy") },
                {"List policies", new Tuple<string,string>("GET /v1/portal/policies/list", "Portal") },
                {"List quotes", new Tuple<string,string>("GET /v1/portal/quotes/list", "Portal") },
                {"Get Quote by ID", new Tuple<string,string>("GET /v1/quotes/{quoteId}", "Quote") },
                {"Confirm Quote", new Tuple<string,string>("POST /v1/quotes/{quoteId}/confirm", "Quote") },
                {"Decline Quote", new Tuple<string,string>("POST /v1/quotes/{quoteId}/decline", "Quote") },
                {"Get Quote Document Content", new Tuple<string,string>("GET /v1/quotes/{quoteID}/documentdata", "Quote") },
                {"Edit Endorsements", new Tuple<string,string>("POST /v1/quotes/{quoteId}/edit/endorsements", "Quote") },
                {"Get Quote Events", new Tuple<string,string>("GET /v1/quotes/{quoteID}/events", "Quote") },
                {"Invalidate Payment Link", new Tuple<string,string>("POST /v1/quotes/{quoteID}/invalidatepaymentlink", "Quote") },
                {"Create Payment Link", new Tuple<string,string>("POST /v1/quotes/{quoteID}/paymentlink", "Quote") },
                {"Get Payment Link", new Tuple<string,string>("GET /v1/quotes/{quoteID}/paymentlink", "Quote") },
                {"Get Quote Payment Plans", new Tuple<string,string>("GET /v1/quotes/{quoteId}/paymentplans", "Quote") },
                {"Get Quote Product", new Tuple<string,string>("GET /v1/quotes/{quoteId}/product", "Quote") },
                {"Refer Quote", new Tuple<string,string>("POST /v1/quotes/{quoteId}/refer", "Quote") },
                {"Withdraw Quote", new Tuple<string,string>("POST /v1/quotes/{quoteId}/withdraw", "Quote") },
                {"Get Quote Withdrawal Reasons", new Tuple<string,string>("GET /v1/quotes/{quoteId}/withdrawalreasons", "Quote") },
                {"List all Quotes", new Tuple<string,string>("GET /v1/quotes/list", "Quote") },
                {"Get Quote Pricing", new Tuple<string,string>("POST /v1/quotes/priceonly", "Quote") },
                {"Get Quote by Reference",new Tuple<string,string>("GET /v1/quotes/reference/{quoteReference}", "Quote") },
                {"Debug Report",new Tuple<string,string>("POST /v1/reporting/debugreport", "Reporting") },
                {"Generate Policy Report (v2)", new Tuple<string,string>("GET /v1/reporting/generatepolicyreport", "Reporting") },
                {"Generate Quote Report (v2)", new Tuple<string,string>("GET /v1/reporting/generatequotereport", "Reporting") },
                {"Report Model", new Tuple<string,string>("GET /v1/reporting/model", "Reporting") },
                {"Policy Report Data (v2)", new Tuple<string,string>("GET /v1/reporting/policyreportdata", "Reporting") },
                {"Reports for Insurer (v2)", new Tuple<string,string>("GET /v1/reporting/reportsforinsurer", "Reporting") },
                {"Send Report", new Tuple<string,string>("POST /v1/reporting/sendreport", "Reporting") },
                {"Send Report by Reference", new Tuple<string,string>("POST /v1/reporting/sendreportbyreference", "Reporting") },
                {"Creates a Report Schedule", new Tuple<string,string>("POST /v1/reportschedule", "Report Schedules") },
                {"Deletes Report Schedule By Id", new Tuple<string,string>("DELETE /v1/reportschedule/{scheduleid}", "Report Schedules") },
                {"Gets Report Schedule By Id", new Tuple<string,string>("GET /v1/reportschedule/{scheduleId}", "Report Schedules") },
                {"Updates Report Schedule", new Tuple<string,string>("PUT /v1/reportschedule/{scheduleId}", "Report Schedules") },
                {"Get Active Report Schedules", new Tuple<string,string>("GET /v1/reportschedule/all", "Report Schedules") },
                {"Search", new Tuple<string,string>("GET /v1/search/policies/{productReference}", "Policy Search") },
                {"Get Policy by ID", new Tuple<string,string>("GET /v1/search/policies/id/{policyId}", "Policy Search") },
                {"Get Policy by reference", new Tuple<string,string>("GET /v1/search/policies/reference/{policyReference}", "Policy Search") },
                {"Create Setup Intent", new Tuple<string,string>("GET /v1/stripe/savedcards/setup", "Stripe") },
                {"Initialise Subscription", new Tuple<string,string>("POST /v1/subscriptions/initialise", "Subscription") },
                {"Update Subscription for mid term adjustment",new Tuple<string,string>("POST /v1/subscriptions/mta", "Subscription") },
                {"TOBES start (question set - new business)", new Tuple<string,string>("GET /v1/tobes/{quoteID}/start", "Tobes") },
                {"TOBES start (question set - mta)", new Tuple<string,string>("GET /v1/tobes/{quoteID}/startmta", "Tobes") },
                {"TOBES start (question set - renewal)", new Tuple<string,string>("GET /v1/tobes/{quoteID}/startrenewal", "Tobes") },
                {"TOBES next", new Tuple<string,string>("POST /v1/tobes/next", "Tobes") },
                {"TOBES quote", new Tuple<string,string>("POST /v1/tobes/nextquote", "Tobes") },
                {"TOBES quote for mid term adjustments", new Tuple<string,string>("POST /v1/tobes/nextquotemta", "Tobes") },
                {"TOBES quote for renewals", new Tuple<string,string>("POST /v1/tobes/nextquoterenewal", "Tobes") },
                {"New quote", new Tuple<string,string>("POST /v1/tobes/quote", "Tobes") },
                {"New quote for mid term adjustment", new Tuple<string,string>("POST /v1/tobes/quotemta", "Tobes") },
                {"New quote for renewal", new Tuple<string,string>("POST /v1/tobes/quoterenewal", "Tobes") },
                {"TOBES start", new Tuple<string,string>("GET /v1/tobes/start", "Tobes") },
                {"TOBES start for mid term adjustments", new Tuple<string,string>("GET /v1/tobes/startmta", "Tobes") },
                {"TOBES start for renewal quotes", new Tuple<string,string>("GET /v1/tobes/startrenewal", "Tobes") },
                {"TOBES update quote", new Tuple<string,string>("POST /v1/tobes/updatequote", "Tobes") },
                {"TOBES update quote for MTAs", new Tuple<string,string>("POST /v1/tobes/updatequotemta", "Tobes") },
                {"TOBES update quote for renewals", new Tuple<string,string>("POST /v1/tobes/updatequoterenewal", "Tobes") },
                {"Use Token", new Tuple<string,string>("POST /v1/token/{token}", "Token") },
                {"Start Session", new Tuple<string,string>("POST /v1/token/{token}/sessionstart", "Token") },
                {"Create user", new Tuple<string,string>("POST /v1/user/create", "User") },
                {"Reset password", new Tuple<string,string>("POST /v1/user/resetpassword", "User") },
                {"Claims Central",new Tuple<string,string>("POST /v1/webhooks/claimscentral", "Webhooks") }
            };

            return dictionary;
        }

        public Dictionary<string, Tuple<string, string>> PlatformEndpointsMap()
        {
            var dictionary = new Dictionary<string, Tuple<string, string>>
            {
                {"Get organisation settings", new Tuple<string,string>("GET /v2/config/organisation", "Config") },
                {"Download document", new Tuple<string,string>("GET /v2/documents/download", "Documents") },
                {"Get Line Of Business configuration", new Tuple<string,string>("GET /v2/lobs/config", "Line Of Business") },
                {"Get Payment", new Tuple<string,string>("GET /v2/payments/{paymentId}", "Payments") },
                {"Get Policy For Payment", new Tuple<string,string>("GET /v2/payments/{paymentId}/policy", "Payments") },
                {"Create Finance Agreement", new Tuple<string,string>("POST /v2/payments/finance", "Payments") },
                {"Update Finance Agreement for mid term adjustment", new Tuple<string,string>("POST /v2/payments/finance/mta", "Payments") },
                {"Initialise Payment", new Tuple<string,string>("POST /v2/payments/initialise", "Payments") },
                {"Refund for a mid term adjustment", new Tuple<string,string>("POST /v2/payments/mtarefund", "Payments") },
                {"One step payment", new Tuple<string,string>("POST /v2/payments/onestep", "Payments") },
                {"Apply Voucher", new Tuple<string,string>("POST /v2/payments/voucher", "Payments") },
                {"Get Policy", new Tuple<string,string>("GET /v2/policies/{policyId}", "Policies") },
                {"Get Policy Add-ons", new Tuple<string,string>("GET /v2/policies/{policyId}/addons", "Policies") },
                {"Get Policy Bundle", new Tuple<string,string>("GET /v2/policies/{policyId}/bundle", "Policies") },
                {"Get Policy Credit Agreement", new Tuple<string,string>("GET /v2/policies/{policyId}/creditagreement", "Policies") },
                {"Get Policy Discount details", new Tuple<string,string>("GET /v2/policies/{policyId}/discountinfo", "Policies") },
                {"Get Policy Payment Method", new Tuple<string,string>("GET /v2/policies/{policyId}/paymentmethod", "Policies") },
                {"Get Policy Product", new Tuple<string,string>("GET /v2/policies/{policyId}/product", "Policies") },
                {"Get Policy Risk", new Tuple<string,string>("GET /v2/policies/{policyId}/risk", "Policies") },
                {"Get Policy Scheme", new Tuple<string,string>("GET /v2/policies/{policyId}/scheme", "Policies") },
                {"Update policy payment method", new Tuple<string,string>("POST /v2/policies/{policyId}/updatepaymentmethod", "Policies") },
                {"Cancel Policy", new Tuple<string,string>("POST /v2/policies/cancel", "Policies") },
                {"Get Policy Cancellation Information", new Tuple<string,string>("GET /v2/policies/cancel/{policyId}/info", "Policies") },
                {"Get My Policies", new Tuple<string,string>("GET /v2/policies/mypolicies", "Policies") },
                {"Get Product (By Reference)", new Tuple<string,string>("GET /v2/product", "Product") },
                {"Get Product (by id)", new Tuple<string,string>("GET /v2/product/{productID}", "Product") },
                {"Generate Quick Quote",new Tuple<string,string>("POST /v2/quickquote", "Quick Quotes") },
                {"Generate a new Quick Quote from partial risk", new Tuple<string,string>("POST /v2/quickquote/frompartialrisk", "Quick Quotes") },
                {"Populate a full risk from the partial risk collected via widgets etc",new Tuple<string,string>("POST /v2/quickquote/populaterisk", "Quick Quotes") },
                {"Get Quote", new Tuple<string,string>("GET /v2/quotes/{quoteId}", "Quotes") },
                {"Get Quote Product", new Tuple<string,string>("GET /v2/quotes/{quoteId}/product", "Quotes") },
                {"Get Quote Risk", new Tuple<string,string>("GET /v2/quotes/{quoteId}/risk", "Quotes") },
                {"Get Quote Scheme", new Tuple<string,string>("GET /v2/quotes/{quoteId}/scheme", "Quotes") },
                {"Associate Quote with User", new Tuple<string,string>("POST /v2/quotes/associatewithuser", "Quotes") },
                {"Email Quote", new Tuple<string,string>("POST /v2/quotes/email", "Quotes") },
                {"Create Setup Intent", new Tuple<string,string>("GET /v2/stripe/savedcards/setup", "Stripe") },
                {"Initialise Subscription", new Tuple<string,string>("POST /v2/subscriptions/initialise", "Subscriptions") },
                {"Update Subscription for mid term adjustment", new Tuple<string,string>("POST /v2/subscriptions/mta", "Subscriptions") },
                {"TOBES next", new Tuple<string,string>("POST /v2/tobes/next", "Tobes") },
                {"TOBES quote", new Tuple<string,string>("POST /v2/tobes/nextquote", "Tobes") },
                {"TOBES quote for mid term adjustments", new Tuple<string,string>("POST /v2/tobes/nextquotemta", "Tobes") },
                {"TOBES quote for renewals", new Tuple<string,string>("POST /v2/tobes/nextquoterenewal", "Tobes") },
                {"New quote", new Tuple<string,string>("POST /v2/tobes/quote", "Tobes") },
                {"New quote for mid term adjustment", new Tuple<string,string>("POST /v2/tobes/quotemta", "Tobes") },
                {"New quote for renewal", new Tuple<string,string>("POST /v2/tobes/quoterenewal", "Tobes") },
                {"TOBES start", new Tuple<string,string>("GET /v2/tobes/start", "Tobes") },
                {"TOBES start for mid term adjustments", new Tuple<string,string>("GET /v2/tobes/startmta", "Tobes") },
                {"TOBES start for renewal quotes", new Tuple<string,string>("GET /v2/tobes/startrenewal", "Tobes") },
                {"Get Current User", new Tuple<string,string>("GET /v2/user/me", "User") }
            };
            return dictionary;
        }
    }
}
